### ISSUE TITLE
Error: RangeError: offset is not uint

### ISSUE THREAD

**Issue by devilankur18** [Ayms/torrent-live#1]
When I running the `node freerider.js ~/torrent_files/<torrent_name>.torrent` its throwing the error as follows

```
launching torrent-live for infohash 08b654463adc33348c678102010f7430917a763f
true infohash 08b654463adc33348c678102010f7430917a763f
fake infohash 08b65446e5aa9b7cd6c81b96800807c43b9a532c
RangeError: offset is not uint
    at checkOffset (buffer.js:580:11)
    at Buffer.readUInt32BE (buffer.js:649:5)
    at generate_id (/Users/user/node_modules/torrent-live/node_modules/bittorrent-nodeid/index.js:14:33)
    at test_bep42 (/Users/user/node_modules/torrent-live/freerider.js:1436:11)
    at addspy (/Users/user/node_modules/torrent-live/freerider.js:728:13)
    at DHT.onpeer (/Users/user/node_modules/torrent-live/freerider.js:788:5)
    at DHT.EventEmitter.emit (events.js:106:17)
    at DHT._addPeer (/Users/user/node_modules/torrent-live/node_modules/bittorrent-dht/client.js:318:10)
    at /Users/user/node_modules/torrent-live/node_modules/bittorrent-dht/client.js:923:9
    at Array.forEach (native) Fri Jun 12 2015
```

**Comment by Ayms** [comment]
Thanks for reporting this, did you build it using npm?

If yes it seems like bittorrent-nodeid is not up to date, but you don't need it at all in fact, it's for specific uses, maybe you can try to install torrent-live again using [the zip file](http://www.peersm.com/torrent-live.zip) or just replace generate_id=require(...) by generate_id=function(){return 'ok'} or something like this in freerider.js

I will look into this (when I have time...)

**Comment by Ayms** [comment]
Or, better, replace var test_bep42=function(id,ip) {...} by var test_bep42=function(id,ip) {return false}

**Comment by Ayms** [comment]
"Corrected" (ie add try/catch for now in bep_42), probably the IP passed to test_bep42 was not correct but I can't know why, if you get a chance to see what IP causes the problem please advise.
